[package]
name = "wavedash-example-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wavedash-example-core = { path = "../core" }
wavedash = { path = "../../" }